### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal ?

### ISSUE THREAD

**Issue by scorpiosnow** [LuyaooChen/uninformed-students-pytorch#3]
python teacher_train.py
...
Traceback (most recent call last):
  File "teacher_train.py", line 61, in <module>
    model = _Teacher(patch_size).to(device)
  File "/home/dit-train-3/anaconda3/envs/pytorch_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/dit-train-3/anaconda3/envs/pytorch_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/dit-train-3/anaconda3/envs/pytorch_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/dit-train-3/anaconda3/envs/pytorch_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/dit-train-3/anaconda3/envs/pytorch_test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

What's happened?

**Comment by LuyaooChen** [comment]
@scorpiosnow  I have 2 GPU in my computer, and I use 'cuda:1' at line 49 `device = torch.device('cuda:1')`. I think you may have just one gpu. Just use 'cuda:0' or 'cpu' to replace it.
